---
-  hosts: all
   become: yes
   gathering_facts: no
   tasks:
   - name: install git, wget, tree on nodes
     apt:
      name: "{{ item }}"
      state: present
     with_itens:
      - git
      - wget
      - tree 

