---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver on nodes
    apt:
      name: apache2
      start: present
    notify: startwebserver

  - name: i want to copy index files into all nodes
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: startwebserver
    
  handlers:
  - name: startwebserver
    service:
      name: apache2
      state: restarted   