---
- hosts: webservers
  become: yes
  tasks: 
  - name: install jdk8 on ubuntu18 node
    apt:
     name: "{{myjavaonubuntuos}}"
     state: present
    when: ansible_os_family == "Debian"
     
        
  
  
