---
- hosts: webservers
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present
      tags:
      - gitpackage
      
  - name: install tree
    apt:
      name: install tree
      state: present
      tags:
      - tree package
      
  - name: install wget
    apt:
      name: install wget
      state: present
      tags:
      - wget package     

