---
- hosts: webservers
  become: yes
  vars:
    myvar1: mani
    myvar2: srinu
  tasks:
  - name: display myvar1
    debug:
      msg: "{{myvar1}}"
  - name: display myvar2
    debug:
      msg: "{{myvar2}}"
            