---
- hosts: all
  become: yes
  tasks:
  - name: install webserver(apache2) on ubuntu18
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"
  - name: start the apache2 server
    service:
     name: apache2
     state: started
    when: ansible_os_family == "Debian"
  - name: install webserver(httpd) on ubuntu18
    apt:
     name: httpd
     state: present
    when: ansible_os_family == "Debian"

  - name: start httpd service
    service:
     name: httpd
     state: started
    when: ansible_os_family == "Debian"
      






